-- Seed all 32 NFL teams (idempotent — skips rows that already exist)
INSERT INTO "Team" (id, name, abbreviation, "espnId")
VALUES
  (gen_random_uuid(), 'Arizona Cardinals',     'ARI', 'ari'),
  (gen_random_uuid(), 'Atlanta Falcons',       'ATL', 'atl'),
  (gen_random_uuid(), 'Baltimore Ravens',      'BAL', 'bal'),
  (gen_random_uuid(), 'Buffalo Bills',         'BUF', 'buf'),
  (gen_random_uuid(), 'Carolina Panthers',     'CAR', 'car'),
  (gen_random_uuid(), 'Chicago Bears',         'CHI', 'chi'),
  (gen_random_uuid(), 'Cincinnati Bengals',    'CIN', 'cin'),
  (gen_random_uuid(), 'Cleveland Browns',      'CLE', 'cle'),
  (gen_random_uuid(), 'Dallas Cowboys',        'DAL', 'dal'),
  (gen_random_uuid(), 'Denver Broncos',        'DEN', 'den'),
  (gen_random_uuid(), 'Detroit Lions',         'DET', 'det'),
  (gen_random_uuid(), 'Green Bay Packers',     'GB',  'gb'),
  (gen_random_uuid(), 'Houston Texans',        'HOU', 'hou'),
  (gen_random_uuid(), 'Indianapolis Colts',    'IND', 'ind'),
  (gen_random_uuid(), 'Jacksonville Jaguars',  'JAX', 'jax'),
  (gen_random_uuid(), 'Kansas City Chiefs',    'KC',  'kc'),
  (gen_random_uuid(), 'Las Vegas Raiders',     'LV',  'lv'),
  (gen_random_uuid(), 'Los Angeles Chargers',  'LAC', 'lac'),
  (gen_random_uuid(), 'Los Angeles Rams',      'LAR', 'lar'),
  (gen_random_uuid(), 'Miami Dolphins',        'MIA', 'mia'),
  (gen_random_uuid(), 'Minnesota Vikings',     'MIN', 'min'),
  (gen_random_uuid(), 'New England Patriots',  'NE',  'ne'),
  (gen_random_uuid(), 'New Orleans Saints',    'NO',  'no'),
  (gen_random_uuid(), 'New York Giants',       'NYG', 'nyg'),
  (gen_random_uuid(), 'New York Jets',         'NYJ', 'nyj'),
  (gen_random_uuid(), 'Philadelphia Eagles',   'PHI', 'phi'),
  (gen_random_uuid(), 'Pittsburgh Steelers',   'PIT', 'pit'),
  (gen_random_uuid(), 'San Francisco 49ers',   'SF',  'sf'),
  (gen_random_uuid(), 'Seattle Seahawks',      'SEA', 'sea'),
  (gen_random_uuid(), 'Tampa Bay Buccaneers',  'TB',  'tb'),
  (gen_random_uuid(), 'Tennessee Titans',      'TEN', 'ten'),
  (gen_random_uuid(), 'Washington Commanders', 'WSH', 'wsh')
ON CONFLICT (name) DO NOTHING;
